---
- name: "Node JS Add Deployment"
  hosts: all
  become: true

  tasks:
  - name: "Checking for app folder"
    command: mkdir -p /home/ubuntu/nodejs_app

  - name: "Copyin files"
    copy: src=./app_code dest=/home/ubuntu/nodejs_app owner=ubuntu group=admin mode=755

  - name: "Deploying nodejs app"
    command: pm2 start /home/ubuntu/nodejs_app/app.js --name 'nodejs app'
    register: deploy

  - name: "Deploying"
    debug:
          var: deploy.stdout_lines
